version: '3'

services:
  db:
    image: postgres:14.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: ConsultVet
    volumes:
      - ./postgres:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend   # Asume que el proyecto NestJS está en la carpeta ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3000:3000"
    depends_on:
      - db  # Asegura que el servicio db (PostgreSQL) se inicie antes que NestJS
